### ISSUE TITLE
Globally queries throws NullPointer Error

### ISSUE THREAD

**Issue by larsbpf** [prismmodelchecker/prism-games#14]
I am currently trying to run Globally queries using prism-games but keep running into the same error, when using Globally, Release and Weak Until. Here is stdout from a run of rock-paper-scissor with the query 'can p1 ensure that p1 never loses':

```
PRISM-games
===========

Version: 3.0.dev (based on PRISM 4.7.dev)
Date: Tue Jun 13 08:40:18 CEST 2023
Hostname: 
Memory limits: cudd=1g, java(heap)=1g
Command line: prism-games rock-paper-scissors.prism p1_never_lose_FALSE.props

Parsing model file "rock-paper-scissors.prism"...

Type:        CSG
Modules:     m1 m2 recorder
Variables:   win

Switching to explicit engine, which supports CSGs...

Parsing properties file "p1_never_lose_FALSE.props"...

2 properties:
(1) <<p1>>P>=1 [ G !(win=2) ]
(2) !<<p1>>P>=1 [ !(true U !(win=2)) ]

---------------------------------------------------------------------

Model checking: <<p1>>P>=1 [ G !(win=2) ]

Building model...

Computing reachable states... 4 states
Reachable states exploration and model construction done in 0.092 secs.
Sorting reachable states list...

Time for model construction: 0.366 seconds.

Type:        CSG
States:      4 (1 initial)
Transitions: 36
Choices:     36
Max/avg:     9/9.00

Starting probabilistic reachability (until)...

java.lang.NullPointerException: Cannot invoke "parser.ast.Coalition.isPlayerIndexInCoalition(int, java.util.Map)" because "<parameter2>" is null
    at explicit.CSGModelChecker.buildCoalitions(CSGModelChecker.java:354)
    at explicit.CSGModelChecker.computeUntilProbs(CSGModelChecker.java:1067)
    at explicit.CSGModelChecker.computeUntilProbs(CSGModelChecker.java:1038)
    at explicit.ProbModelChecker.checkProbUntil(ProbModelChecker.java:1131)
    at explicit.ProbModelChecker.checkProbPathFormulaSimple(ProbModelChecker.java:930)
    at explicit.ProbModelChecker.checkProbPathFormula(ProbModelChecker.java:890)
    at explicit.ProbModelChecker.checkExpressionProb(ProbModelChecker.java:846)
    at explicit.ProbModelChecker.checkExpressionStrategy(ProbModelChecker.java:599)
    at explicit.ProbModelChecker.checkExpression(ProbModelChecker.java:530)
    at explicit.StateModelChecker.checkExpressionFilter(StateModelChecker.java:1108)
    at explicit.StateModelChecker.checkExpression(StateModelChecker.java:724)
    at explicit.NonProbModelChecker.checkExpression(NonProbModelChecker.java:76)
    at explicit.ProbModelChecker.checkExpression(ProbModelChecker.java:550)
    at explicit.StateModelChecker.check(StateModelChecker.java:639)
    at prism.Prism.modelCheck(Prism.java:3214)
    at prism.PrismCL.run(PrismCL.java:397)
    at prism.PrismCL.go(PrismCL.java:223)
    at prism.PrismCL.main(PrismCL.java:2669)

Error: Caught unhandled exception, aborting....
```
The CSG is defined as follows:

```
// Rock paper scissors
csg

player p1 m1 endplayer
player p2 m2 endplayer

// first player
module m1
        [r1] true -> true; // rock
        [p1] true -> true; // paper
        [s1] true -> true; // scissors

endmodule

// second player constructed through renaming
module m2 = m1[r1=r2,p1=p2,s1=s2] endmodule

// module to record who wins
module recorder

        win : [-1..2];

        [r1,r2] true -> (win'=0);
        [r1,p2] true -> (win'=2);
        [r1,s2] true -> (win'=1);

        [p1,r2] true -> (win'=1);
        [p1,p2] true -> (win'=0);
        [p1,s2] true -> (win'=2);

        [s1,r2] true -> (win'=2);
        [s1,p2] true -> (win'=1);
        [s1,s2] true -> (win'=0);
endmodule
```

**Comment by davexparker** [comment]
Can you try with a more recent version? I can recreate this with 3.1 (already newer than what you use, it seems), but it is fixed in the latest code:

https://github.com/prismmodelchecker/prism-games
